on: 
  pull_request:
    types: [labeled]
    
name: "Bypass review"


jobs:
  automerge:
    runs-on: linux
    steps:
      - name: Check PR label
        if: github.event.label.name == 'bypass-review'
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge
        if: ${{ success() }}
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          method: merge

      - name: Cancel
        if: ${{ failure() }}
        run:
          echo Not merging. Cancelled.
