name: codespell
on: [pull_request, push]
jobs:
  codespell:
    #    if: github.event.pull_request.user.type != 'Bot' && !contains(github.event.pull_request.labels.*.name, 'skip-ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4
      - run: pip install codespell==2.1.0
      - run:
          codespell --ignore-words-list="groupt,nd,ot,ro,falsy,BU,invokable" \
          --exclude-file=".github/workflows/codespell.yml"
