name: codespell
on: [pull_request, push]
jobs:
  codespell:
#    if: github.event.pull_request.user.type != 'Bot' && !contains(github.event.pull_request.labels.*.name, 'skip-ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install codespell
      - run: codespell --ignore-words-list="groupt,nd,ot"
