name: "Documentation Checks"

on:
  push:
    paths:
      - "discord/**"
      - "docs/**"
      - "requirements/**"
      - "*.toml"
      - "*.py"
    branches: [master]
  pull_request:
    paths:
      - "discord/**"
      - "docs/**"
      - "requirements/"
      - "*.toml"
      - "*.py"
  workflow_dispatch:
    inputs:
      with_linkcheck:
        type: boolean
        description: "Whether to run the linkcheck"
        default: true
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5
      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Sync dependencies
        run: uv sync --no-python-downloads --group dev --group docs
      - name: "Check Links"
        env:
          SPHINXBUILD: ${{ github.workspace }}/.venv/bin/sphinx-build
        if: ${{ github.event_name == 'schedule' || inputs.with_linkcheck }}
        run: |
          cd docs
          make linkcheck
      - name: "Compile to html"
        env:
          SPHINXBUILD: ${{ github.workspace }}/.venv/bin/sphinx-build
        run: |
          cd docs
          make -e SPHINXOPTS="-D language='en'" html
