name: "Sync Guild Features"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,5'


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  sync-guild-features:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for all branches
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Sync dependencies
        run: uv sync --no-python-downloads --group dev --group ci
      - name: "Run guild features sync"
        run: uv run python -m scripts.sync_guild_features
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
