name: Version Update Auto Merge
on: [pull_request, workflow_dispatch]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if:
      ${{ github.actor == 'dependabot[bot]' || github.actor == 'crowdin-bot' ||
      github.actor == 'Crowdin Bot' }}
    steps:
      - run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: gh pr merge --auto -d --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
